package utils;

public enum TipoToken {
    IDENTIFICADOR, 
    RESERVADA, 
    NUMERO_INTEIRO,
    NUMERO_REAL,
    OPERADOR_ARITMETICO,
    OPERADOR_RELACIONAL,
    OPERADOR_LOGICO,
    SIMBOLO, 
    FIM_ARQUIVO,
    ERRO, 
    COMENTARIO, 
    LITERAL_STRING
}
